Add estimate_fee to Account
software-mansion/starknet.py pull request #1279
Opened 2024-02-06 14:15 UTC by tkumor3

Closes #

## Introduced changes

- 
- 

##

- [ ] This PR contains breaking changes

2024-02-07 10:54 UTC, ddoktorski commented on starknet_py/net/account/account.py
>          """
The docstring here seems redundant now, as having it in the `BaseClass` already provides the necessary information.

2024-02-07 11:05 UTC, ddoktorski commented on starknet_py/net/account/base_account.py
> +        :return: Estimated fee of transactions.
```suggestion
        :param tx: Transaction or list of transactions to estimate
        :param skip_validate: Flag checking whether the validation part of the transaction should be executed
        :param block_hash: Block hash or literals `"pending"` or `"latest"`
        :param block_number: Block number or literals `"pending"` or `"latest"`
        :return: Estimated fee or list of estimated fees for each transaction
```

2024-02-07 11:26 UTC, ddoktorski commented on starknet_py/net/account/account.py
> +            tx=ttx,
```suggestion
        transactions = (
            await self.sign_for_fee_estimate(tx)
            if isinstance(tx, AccountTransaction)
            else [await self.sign_for_fee_estimate(t) for t in tx]
        )
        
        return await self._client.estimate_fee(
            tx=transactions,
```

2024-02-07 11:27 UTC, ddoktorski commented on starknet_py/tests/e2e/account/account_test.py
> +async def test_account_estimate_fee_for_declare_transaction(
Could we also add a test for multiple transactions?

2024-02-07 11:46 UTC, tkumor3 commented on starknet_py/net/account/account.py
> +            tx=ttx,
That is in more python way 🔥

2024-02-07 14:38 UTC, ddoktorski commented on starknet_py/tests/e2e/account/account_test.py
> +    )
```suggestion
    declare_tx = await account.sign_declare_v1(
        compiled_contract=map_compiled_contract, max_fee=MAX_FEE
    )
    declare_tx2 = await account.sign_declare_v1(
        compiled_contract=map_compiled_contract,
        max_fee=MAX_FEE,
        nonce=declare_tx.nonce + 1
    )
```

2024-02-07 14:42 UTC, ddoktorski commented on starknet_py/tests/e2e/account/account_test.py
> +    estimated_fee = await account.estimate_fee(tx=[declare_tx, declare_tx2])
Can we have two distinct transaction types? I believe it would be even better if the second transaction were in version 3.

2024-02-09 09:31 UTC, ddoktorski requested changes
I've noticed that some of the previous comments I made have not been completely addressed yet. Please check it and request a review again once it's ready.

2024-02-09 13:33 UTC, ddoktorski commented on starknet_py/tests/e2e/account/account_test.py
> +
Could we also include the following assertions?
```
assert len(estimated_fee) == 2
assert estimated_fee[0].unit == PriceUnit.WEI
assert estimated_fee[1].unit == PriceUnit.FRI
```

2024-02-09 13:34 UTC, ddoktorski commented on starknet_py/tests/e2e/account/account_test.py
> +    estimated_fee = await account.estimate_fee(tx=[declare_tx, inveke_tx])
```suggestion
    invoke_tx = await account.sign_invoke_v3(
        calls=Call(map_contract.address, get_selector_from_name("put"), [3, 4]),
        l1_resource_bounds=MAX_RESOURCE_BOUNDS_L1,
        nonce=(declare_tx.nonce + 1),
    )

    estimated_fee = await account.estimate_fee(tx=[declare_tx, invoke_tx])
```

2024-02-09 14:36 UTC, ddoktorski approved these changes
It would be nice to include this change in the guide in our documentation. Given that there are some fee estimation related changes in the next Starknet `0.13.1` version, it can be done in a separate PR.

2024-02-15 07:47 UTC, merged