Parallelize e2e tests
software-mansion/starknet.py pull request #136
Opened 2022-04-29 15:17 UTC by cptartur

### **Please check if the PR fulfills these requirements**
- [ ] The formatter, linter, and tests all run without an error
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Attempt to parallelize e2e tests

* **What is the current behavior?** (You can also link to an open issue here)

All e2e tests run on single thread

## **What is the new behavior (if this is a feature change)?**

Each e2e test module runs on separate thread

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

## **Other information**

This is work in progress, I will keep this PR as draft until I've done enough testing to see if this parallelization doesn't lead to any unpredictable problems.

2022-05-04 14:45 UTC, cptartur commented
I believe it would also (partially) resolve #134

2022-05-05 06:44 UTC, Solpatium requested changes

2022-05-05 06:44 UTC, Solpatium commented on starknet_py/tests/e2e/conftest.py
> +    os.environ["DEVNET_PORT"] = str(devnet_port)
I think this is not needed.

2022-05-06 09:54 UTC, Solpatium approved these changes

2022-05-09 08:09 UTC, merged