feat: from_keystore method
software-mansion/starknet.py pull request #1371
Opened 2024-06-26 14:21 UTC by EvolveArt

Closes #1368 

## Introduced changes

- Adds https://pypi.org/project/eth-keyfile/ as a dependency
- Adds a `from_keystore` method to the `KeyPair` class

##

- [ ] This PR contains breaking changes

2024-06-27 14:35 UTC, ddoktorski requested changes
Thank you for your contribution! I've left a few minor comments that need to be addressed before merging :)

2024-06-27 14:35 UTC, ddoktorski commented on poetry.lock
Could you please update the dependencies using `poetry update eth-keyfile`? This way we can avoid updating dependencies that are not relevant for this change.

2024-06-27 14:35 UTC, ddoktorski commented on pyproject.toml
What's the reason to format the `pyproject.toml` file?

2024-06-27 14:35 UTC, ddoktorski commented on starknet_py/net/signer/stark_curve_signer.py
> +        :param path: Path to the keystore file.
A newline is necessary for correct formatting in the docs.
```suggestion
        The keystore file should follow the Ethereum keystore format.
        
        :param path: Path to the keystore file.
```

2024-06-27 17:42 UTC, EvolveArt commented on pyproject.toml
just ran `poe format` in the repo

2024-06-27 18:06 UTC, EvolveArt commented on pyproject.toml
reverted

2024-06-27 18:06 UTC, EvolveArt commented on poetry.lock
done

2024-06-28 13:17 UTC, ddoktorski approved these changes
Thank you! LGTM 🔥 

_Note: Tests on network fail due to unset secrets in the fork repository_

2024-06-28 13:18 UTC, merged