Run lint on tests
software-mansion/starknet.py pull request #138
Opened 2022-05-04 14:29 UTC by cptartur

### **Please check if the PR fulfills these requirements**
- [ ] The formatter, linter, and tests all run without an error
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Closes #137

2022-05-05 06:36 UTC, Solpatium requested changes

2022-05-05 06:36 UTC, Solpatium commented on starknet_py/tests/e2e/contract_interaction/interaction_test.py
> +    prepared_call.hash  # pylint: disable=pointless-statement
Why do we need this statement?

2022-05-05 06:36 UTC, Solpatium commented on starknet_py/tests/e2e/contract_interaction/interaction_test.py
> +    prepared_call.hash  # pylint: disable=pointless-statement
If is throws when hash is not defined I suggest using `assert hasattr(prepared_call, "hash")` to be explicit.

2022-05-06 13:02 UTC, Arcticae approved these changes

2022-05-09 07:17 UTC, merged