Enum moved form schemas/common.py to schemas/revisions
software-mansion/starknet.py pull request #1500
Opened 2024-09-30 10:09 UTC by manicdon7

Closes #

## Introduced changes

Enum moved form schemas/common.py to schemas/revisions
- 
- 

##

- [ ] This PR contains breaking changes

2024-09-30 14:02 UTC, franciszekjob requested changes
Please fix tests and lint.

2024-10-02 08:51 UTC, franciszekjob requested changes

2024-10-02 08:51 UTC, franciszekjob commented on pyproject.toml
Please don't change `pyright` version.

2024-10-02 08:51 UTC, franciszekjob commented on requirements.txt
Not needed.

2024-10-02 10:24 UTC, manicdon7 commented on pyproject.toml
Sure I'll change that to previous version

2024-10-02 10:24 UTC, manicdon7 commented on requirements.txt
Sure I'll remove it
and again raise a PR

2024-10-03 15:29 UTC, manicdon7 commented
updated the changes

2024-10-03 22:21 UTC, closed without merging

2024-10-04 00:46 UTC, manicdon7 commented
I have passed the required tests and linting. Still my request has been
closed.

On Fri, Oct 4, 2024, 3:51 AM Franciszek Job ***@***.***>
wrote:

> Closed #1500 <https://github.com/software-mansion/starknet.py/pull/1500>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/software-mansion/starknet.py/pull/1500#event-14510942078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARCPJVZFHJ44RJLKQWDFCNLZZW7PVAVCNFSM6AAAAABPC5WWHOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUGUYTAOJUGIYDOOA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-10-04 09:51 UTC, franciszekjob commented
You've modified dependency version which was not needed.

2024-10-04 11:53 UTC, manicdon7 commented
If I kept same version it was ended in test fail.

On Fri, Oct 4, 2024, 3:21 PM Franciszek Job ***@***.***>
wrote:

> You've modified dependency version which was not needed.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/software-mansion/starknet.py/pull/1500#issuecomment-2393310970>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARCPJVZI2BYVJNIRHR6ES7DZZZQLBAVCNFSM6AAAAABPC5WWHOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJTGMYTAOJXGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>