Update/0.9.1
software-mansion/starknet.py pull request #238
Opened 2022-07-12 09:44 UTC by war-in

### **Please check if the PR fulfills these requirements**
- [ ] The formatter, linter, and tests all run without an error
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

It adds changes from cairo 0.9.1

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

2022-07-12 10:42 UTC, cptartur commented on starknet_py/net/rpc_schemas/rpc_schemas.py
> +    starknet_version = fields.String(data_key="starknet_version")
I don't think the version of the RPC we support (0.15) has this fields. I think it'd be better to have it with `load_default` here.

2022-07-12 10:42 UTC, cptartur commented on starknet_py/net/client_models.py
> +    declared_contracts: List[hex]
I prefer we stick to using integers where possible

2022-07-12 10:42 UTC, cptartur commented on starknet_py/net/gateway_schemas/gateway_schemas.py
> +        declared_contracts = data["state_diff"]["declared_contracts"]
I'd prefer this had its' own schema like `ContractDiffSchema` and `StorageDiffSchema` even if it's just a single field.

2022-07-20 14:37 UTC, Arcticae requested changes
All seems good apart from that one

2022-07-21 08:49 UTC, Arcticae approved these changes

2022-07-21 09:09 UTC, cptartur reviewed
I'm not quite sure about adding starknet_version to block as a optional field. Do you know if newer versions of rpc spec also added this field?

2022-07-21 09:09 UTC, cptartur commented on pyproject.toml
> +cairo-lang = "^0.9.1"
I prefer we used specific cairo-lang version like it was done before.

2022-07-21 09:37 UTC, ca11ab1e commented
> I'm not quite sure about adding starknet_version to block as a optional field. Do you know if newer versions of rpc spec also added this field?

From the 0.9.1 patch, `starknet_version` was only added to `BlockInfo` (https://github.com/starkware-libs/cairo-lang/blob/13cef109cd811474de114925ee61fd5ac84a25eb/src/starkware/starknet/business_logic/state/state.py#L63).

2022-07-21 10:35 UTC, merged

2022-07-21 21:27 UTC, Pet3ris commented
Yay