Cairo files refactor and tests speed up
software-mansion/starknet.py pull request #250
Opened 2022-07-19 12:58 UTC by war-in

### **Please check if the PR fulfills these requirements**
- [ ] The formatter, linter, and tests all run without an error
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

It moves .cairo files to one directory and adds fixtures to deploy the most used contracts only once per package.

* **What is the current behavior?** (You can also link to an open issue here)

.cairo files are in different folders and are duplicated. Contracts like map.cairo are deployed in many tests (deploys are slow)

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

2022-07-20 13:50 UTC, Arcticae requested changes

2022-07-20 13:50 UTC, Arcticae commented on starknet_py/tests/e2e/client/conftest.py
> +    script_path = Path(directory + "/prepare_devnet_for_gateway_test.sh")
these days i tend to prefer this style of merging paths:
`    script_path = Path(directory) / "prepare_devnet_for_gateway_test.sh"`

2022-07-21 06:18 UTC, war-in commented on starknet_py/tests/e2e/conftest.py
> +@pytest.fixture(name="gateway_client", scope="module")
Firstly, because account_client fixture uses it and its scope is a module. Secondly, it is ok for us because we don't need a new one everywhere.

2022-07-22 11:01 UTC, Arcticae requested changes

2022-07-22 11:01 UTC, Arcticae commented on starknet_py/tests/e2e/conftest.py
> +    map_source_code = (directory_with_contracts / "map.cairo").read_text("utf-8")
we could define those at module-level so it would be reusable

2022-07-22 11:29 UTC, Arcticae approved these changes

2022-07-22 11:46 UTC, merged