Update ProxyCheck
software-mansion/starknet.py pull request #270
Opened 2022-07-28 09:24 UTC by drknzz

### **Please check if the PR fulfills these requirements**
- [x] The formatter, linter, and tests all run without an error
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Updates ProxyCheck subclasses.

Tests for OpenZeppelinProxyCheck and ArgentProxyCheck based on [OZ cairo contract](https://github.com/OpenZeppelin/cairo-contracts/blob/243df2b0935b09366ee08785c7cb3634c22c3642/src/openzeppelin/upgrades/presets/Proxy.cairo) and [Argent cairo contract](https://github.com/argentlabs/argent-contracts-starknet/blob/21466061765626824831d6304b9255b0d38338e7/contracts/Proxy.cairo)

## **What is the current behavior?** (You can also link to an open issue here)
Out of date ProxyCheck subclasses.

## **What is the new behavior (if this is a feature change)?**
OpenZeppelinProxyCheck subclasses are updated and pass the tests.

2022-07-28 10:38 UTC, cptartur reviewed
Would it be possible to use `pytest.mark.parametrize` instead of for loops in tests? Having for loops makes test outputs less readable since it's not immediately know which iteration failed.

2022-08-09 11:05 UTC, war-in approved these changes
Perfect! Just one question

2022-08-09 11:40 UTC, cptartur requested changes

2022-08-09 11:40 UTC, cptartur commented on starknet_py/tests/e2e/proxy_check/proxy_test.py
> +
Here we wait for acceptance but in the above and below test we don't. We should wait in other cases as well.

2022-08-09 11:40 UTC, cptartur commented on starknet_py/tests/e2e/proxy_check/proxy_test.py
> +        )
Can this at least be abstracted into separate methods? It makes this test unnecessarily complicated.

2022-08-09 13:15 UTC, cptartur approved these changes
Just a sigle comment, otherwise approved.

2022-08-09 13:15 UTC, cptartur commented on starknet_py/tests/e2e/proxy_check/proxy_test.py
> +    )
Check if these should be awaited

2022-08-09 13:28 UTC, merged