StarknetChainId replaced with ChainId
software-mansion/starknet.py pull request #300
Opened 2022-08-10 10:19 UTC by war-in

### **Please check if the PR fulfills these requirements**
- [ ] The formatter, linter, and tests all run without an error
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Closes #297 

* **What is the current behavior?** (You can also link to an open issue here)

ChainId can be only StarknetChainId

## **What is the new behavior (if this is a feature change)?**

ChainId can be int too

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

## **Other information**

2022-08-17 10:19 UTC, Arcticae requested changes

2022-08-17 10:19 UTC, Arcticae commented on starknet_py/net/models/transaction.py
> +        chain_id=chain_id if isinstance(chain_id, int) else chain_id.value,
i'd do it another way around - check if it's an enum, and only then get `.value`

2022-08-17 10:19 UTC, Arcticae commented on starknet_py/net/models/transaction.py
> +        chain_id=chain_id if isinstance(chain_id, int) else chain_id.value,
same here

2022-08-17 10:19 UTC, Arcticae commented on starknet_py/net/signer/stark_curve_signer.py
> +            else self.chain_id.value,
and here

2022-08-23 09:37 UTC, cptartur reviewed
I'd add some test verifying if passing custom chain id works properly.

2022-09-21 11:34 UTC, closed without merging