feat: add gas_price to GatewayBlock
software-mansion/starknet.py pull request #316
Opened 2022-08-18 17:49 UTC by unparalleled-js

### **Please check if the PR fulfills these requirements**
- [ ] The formatter, linter, and tests all run without an error
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* Adds `gas_price` to blocks from the Starknet gateway.

* **What is the current behavior?** (You can also link to an open issue here)

gas_price is not available even though it is present in the Gateway block response.

## **What is the new behavior (if this is a feature change)?**

Now, when using the gateway client, you have access to the gas price from the block schema

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No breaking change.

## **Other information**

Previous PR was closed because it got stale. Sorry about that!

2022-08-19 08:23 UTC, war-in requested changes
Thanks for contributing! Could you please address my comments?

2022-08-19 08:23 UTC, war-in commented on starknet_py/tests/e2e/client/client_test.py
> +    fullnode_client = clients[1]
There are two fixtures: gateway_client and rpc_client, so you could use them instead of "clients"

2022-08-19 08:23 UTC, war-in commented on starknet_py/tests/e2e/client/client_test.py
> +        **vars(expected_fullnode_block), gas_price=100_000_000_000
Where is this gas_price value come from? Maybe there is a way to parameterize it?

2022-08-19 08:23 UTC, war-in commented on starknet_py/tests/e2e/client/client_test.py
> +    fullnode_client = clients[1]
same as above

2022-08-19 08:23 UTC, war-in commented on starknet_py/tests/e2e/client/client_test.py
> +        **vars(expected_fullnode_block), gas_price=100_000_000_000
same as above

2022-08-23 08:00 UTC, cptartur requested changes

2022-09-23 07:00 UTC, war-in commented
Hey 👋  We can't merge this PR, because of some conflicts :/ Also, could you address @cptartur's review? We would be happy to have it merged 🙂

2022-09-23 15:38 UTC, unparalleled-js commented
> Hey 👋 We can't merge this PR, because of some conflicts :/ Also, could you address @cptartur's review? We would be happy to have it merged 🙂

I tried to address the conflicts but it seemed complicated and haven't had time, so I will have to circle back when I have time.

2022-09-26 07:23 UTC, cptartur commented
It seems like pylint checks are failing. Could you address that?

2022-09-27 06:29 UTC, war-in requested changes
All seems good and simple! Nice PR, just a few comments

2022-09-27 06:29 UTC, war-in commented on starknet_py/net/client_models.py
> +    gas_price: int
I would also add this as a `GatewayClient.get_block` return type

2022-09-27 06:29 UTC, war-in commented on starknet_py/tests/e2e/conftest.py
> +    return StarknetGeneralConfig().min_gas_price
We are trying to describe all of our fixtures to exactly know what they are responsible for, so please do it here 🙏

2022-09-27 06:29 UTC, war-in commented on starknet_py/tests/e2e/conftest.py
> +    return StarknetGeneralConfig().min_gas_price
Also please add a return type :)

2022-09-28 06:18 UTC, war-in approved these changes

2022-09-28 07:53 UTC, cptartur approved these changes

2022-09-28 08:12 UTC, merged