0.4.8 migration guide
software-mansion/starknet.py pull request #343
Opened 2022-08-31 13:22 UTC by drknzz

### **Please check if the PR fulfills these requirements**
- [ ] The formatter, linter, and tests all run without an error
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

## **What is the new behavior (if this is a feature change)?**

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

## **Other information**

2022-09-02 08:44 UTC, war-in commented on docs/migration_guide.rst
> +- ``contract_address`` field is now called ``account_contract_address``
It hasn't chanded. It is mentioned in the notion, but there is no difference in the package

2022-09-02 08:44 UTC, war-in commented on docs/migration_guide.rst
> +0.4.8 of starknet.py brings fresh changes including a breaking change in contracts' code.
Maybe we should mention that this breaking change doesn't come from starknet.py?

2022-09-05 07:10 UTC, Solpatium requested changes

2022-09-05 07:10 UTC, Solpatium commented on docs/migration_guide.rst
> +
Add a note that informs users that they can use the previous version if they don't need any new features.

2022-09-05 08:49 UTC, Solpatium approved these changes

2022-09-05 08:50 UTC, merged

2022-09-05 08:51 UTC, cptartur reviewed
One question, otherwise looks very good

2022-09-05 08:51 UTC, cptartur commented on docs/migration_guide.rst
> +    There is no need to upgrade ``starknet.py`` to the newest version because the old one is still compatible with StarkNet.
Are we sure about this line?