Add an information about "supported_tx_version" to Quickstart
software-mansion/starknet.py pull request #372
Opened 2022-09-20 06:54 UTC by war-in

### **Please check if the PR fulfills these requirements**
- [ ] The formatter, linter, and tests all run without an error
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Closes #371 

## **What is the current behavior?** (You can also link to an open issue here)

`supported_tx_version` is mentioned only in the migration guide

## **What is the new behavior (if this is a feature change)?**

It is present in the quickstart

## **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

## **Other information**

2022-09-20 09:26 UTC, cptartur approved these changes
Looks fine to me, but I'd wait for @Solpatium opinion.

2022-09-21 10:13 UTC, Solpatium requested changes

2022-09-21 11:01 UTC, Solpatium commented on starknet_py/tests/e2e/docs/quickstart/test_creating_account_client.py
> +    # new AccountClient using transaction version=1 (does have __validate__ function)
has `__validate__`...

2022-09-21 11:02 UTC, Solpatium approved these changes
Just one small change required

2022-09-21 13:31 UTC, merged