Update compiled contracts
software-mansion/starknet.py pull request #408
Opened 2022-09-30 11:03 UTC by drknzz

### **Please check if the PR fulfills these requirements**
- [x] The formatter, linter, and tests all run without an error
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Compiled contracts are in the same directory as their source code.
These contracts were compiled manually with `starknet-compile` version < 0.10.0

Changes introduced:
- **`poe compile_contracts`** - runs `compile_contracts.sh` which compiles every contract's source code in `mock/contracts` and outputs it's `abi` and `compiled contract` into `mock/contracts_compiled`
- before developing, one must run the command above to generate compiled contracts and store them locally (directory with compilation outputs is added to .gitignore)
- remove all occurrences of hardcoded compiled contracts
- fix `proxy_test` as contracts compiled with `starknet-compile` v0.10.0 in their `abi` do not have external functions from namespaces (which was the case before 0.10.0)
- update github action to compile contracts before testing
- update docs

2022-09-30 12:30 UTC, war-in commented on starknet_py/tests/e2e/mock/contracts/oz_proxy.cairo
> +}
I'm not sure if we should edit this file at all. We want to add some licence and these changes are probably unwanted. cc @cptartur

2022-09-30 12:30 UTC, war-in commented on starknet_py/tests/e2e/mock/contracts/user_balance.cairo
> +%lang starknet
It can be deleted (entire file). We do not use it

2022-09-30 12:30 UTC, war-in commented on starknet_py/tests/e2e/proxy_check/proxy_test.py
> +        "_set_implementation" if argent_proxy else "set_implementation_hash"
Connected with `oz` file modification

2022-09-30 12:30 UTC, war-in commented on starknet_py/tests/e2e/client/conftest.py
> +    ).read_text("utf-8")
If we change all `contract_source` to `contract_compiled` we should save some time. Tests will be faster 🔥

2022-09-30 12:30 UTC, war-in commented on starknet_py/tests/e2e/client/conftest.py
> +    ).read_text("utf-8")
Of course not in tests testing contract compilation 😅

2022-11-10 14:13 UTC, Solpatium requested changes

2022-11-10 14:13 UTC, Solpatium commented on starknet_py/tests/e2e/conftest.py
> +    )
Do we only use OZ proxies here?

2022-11-10 14:22 UTC, drknzz commented on starknet_py/tests/e2e/deploy/deploy_test.py
> +)
Each contract is read only once, but reading all of them in one place is a good idea.

2022-11-10 14:24 UTC, drknzz commented on starknet_py/tests/e2e/mock/compile_contracts.sh
> +#!/bin/bash
It's modified version of what [starknet-devnet](https://github.com/Shard-Labs/starknet-devnet/blob/master/scripts/compile_contracts.sh) has.

2022-11-10 15:39 UTC, THenry14 commented on starknet_py/tests/e2e/mock/compile_contracts.sh
> +#!/bin/bash
This script looks fine :+1:

2022-11-14 10:13 UTC, merged