Parametrize client_test.py
software-mansion/starknet.py pull request #437
Opened 2022-10-07 13:46 UTC by drknzz

Closes #422 

### **Please check if the PR fulfills these requirements**
- [x] The formatter, linter, and tests all run without an error
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- disable full node client when running tests on integration / testnet
- parametrize client_test.py

2022-10-07 13:54 UTC, war-in commented on requirements.txt
> +lark==0.12.0 ; python_version >= "3.8" and python_version < "3.10"
👀

2022-10-07 13:54 UTC, war-in commented on starknet_py/tests/e2e/client/conftest.py
> +    Return client names based on network in sys.argv
`Return client fixtures names...`?

2022-10-07 13:54 UTC, war-in commented on starknet_py/tests/e2e/docs/guide/test_full_node_client.py
> -    full_node_client = rpc_client
We can't do that :/ our `full_node_client` fixture will be overrided

2022-10-07 13:54 UTC, war-in commented on starknet_py/tests/e2e/docs/quickstart/test_using_full_node_client.py
> -    full_node_client = rpc_client
And again :/

2022-10-07 13:59 UTC, cptartur requested changes

2022-10-07 13:59 UTC, cptartur commented on requirements.txt
> +lark==0.12.0 ; python_version >= "3.8" and python_version < "3.10"
Please regenerate requirements.txt and make sure these are needed.

2022-10-07 13:59 UTC, cptartur commented on starknet_py/tests/e2e/client/client_test.py
>          )
These should go to their respective files instead of `test_client`

2022-10-07 13:59 UTC, cptartur commented on starknet_py/tests/e2e/client/client_test.py
> +        kwargs["block_number"] = "latest"
Can't we use `latest` in both clients?

2022-10-07 13:59 UTC, cptartur commented on starknet_py/tests/e2e/client/client_test.py
>      )
This should be in full node client tests file.

2022-10-10 06:02 UTC, war-in reviewed
Perfect! Just one suggestion

2022-10-10 06:02 UTC, war-in commented on starknet_py/tests/e2e/conftest.py
>  def rpc_account_client(
Maybe we should change this name too? `full_node_account_client`?

2022-10-10 07:34 UTC, cptartur approved these changes

2022-10-10 09:17 UTC, merged