Add 0.16.0 migration guide
software-mansion/starknet.py pull request #821
Opened 2023-03-03 10:31 UTC by cptartur

Closes #819 

## Introduced changes

- Added a migration guide for changes introduced in version 0.16.0 (also related to Starknet 0.11.0)

##

- [ ] This PR contains breaking changes

2023-03-03 10:48 UTC, war-in requested changes

2023-03-03 10:48 UTC, war-in commented on docs/migration_guide.rst
>  0.15.0 Migration guide
0.15.0 is not released yet 😅

2023-03-03 10:48 UTC, war-in commented on docs/migration_guide.rst
> +1. Removed deprecated ``AccountClient``
I once got a comment from someone that we do not have to write `deprecated` everywhere. 
Maybe let's write which class should be used instead?

2023-03-03 11:08 UTC, cptartur commented on docs/migration_guide.rst
>  0.15.0 Migration guide
🤦 Will combine 0.15.0 and 0.16.0 then

2023-03-06 07:06 UTC, war-in commented on docs/migration_guide.rst
> +It also adds initial support for Starknet 0.11.0 and related changes.
I would change the order of these two sentences. From the user's perspective, 0.11 is more important

2023-03-06 07:07 UTC, war-in commented
Docs are failing. Could you resolve that?

2023-03-06 12:02 UTC, cptartur commented
> Docs are failing. Could you resolve that?

Should be working now.

2023-03-06 12:11 UTC, war-in approved these changes

2023-03-06 12:11 UTC, merged